import PDFDocument from 'pdfkit';
import path from 'path';
import * as fs from 'fs';

import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function generatePDFReport(aiReport, sessionId) {
    return new Promise((resolve, reject) => {
        try {
            const reportsDir = path.join(__dirname, 'reports');

            if (!fs.existsSync(reportsDir)) {
                fs.mkdirSync(reportsDir, { recursive: true });
            }

            const pdfPath = path.join(reportsDir, `report_${sessionId}.pdf`);
            const doc = new PDFDocument({
                margin: 0,
                size: 'A4' // 595.28 x 841.89
            });
            const stream = fs.createWriteStream(pdfPath);
            doc.pipe(stream);

            // Helper to draw the global Navy Header
            const drawGlobalHeader = (pageNumber = null) => {
                doc.rect(0, 0, doc.page.width, 60).fill('#0B172A'); // Dark Navy

                doc.fillColor('#FFFFFF')
                    .font('Helvetica-Bold')
                    .fontSize(12)
                    .text('Property Due Diligence Risk Report', 40, 25);

                doc.font('Helvetica')
                    .fontSize(9)
                    .text('0 best • higher = higher risk', doc.page.width - 200, 26, { align: 'right' });

                if (pageNumber) {
                    doc.fillColor('#6B7280')
                        .fontSize(9)
                        .text(`Generated by Risk Engine`, 40, 80)
                        .text(`Page ${pageNumber}`, doc.page.width - 80, 80);
                }
            };

            // Calculate colors and text based on risk
            let riskBgColor = '#DCFCE7'; // Green
            let riskTextColor = '#166534';
            let riskLevelBoxFill = '#22C55E';
            let riskText = 'LOW RISK';

            if (aiReport.riskLevel === 'High') {
                riskBgColor = '#FFE4E6'; // Red
                riskTextColor = '#991B1B';
                riskLevelBoxFill = '#EF4444';
                riskText = 'HIGH RISK';
            } else if (aiReport.riskLevel === 'Medium') {
                riskBgColor = '#FEF3C7'; // Yellow/Orange
                riskTextColor = '#92400E';
                riskLevelBoxFill = '#F59E0B';
                riskText = 'MEDIUM RISK';
            }

            // --- COVER PAGE ---
            drawGlobalHeader();

            let yPos = 120;
            const leftMargin = 80;
            const contentWidth = doc.page.width - 160;

            // Title
            doc.fillColor('#000000')
                .font('Helvetica-Bold')
                .fontSize(24)
                .text('Property Due Diligence Risk Report', leftMargin, yPos);
            yPos += 40;

            // Subtext
            doc.font('Helvetica')
                .fontSize(10)
                .text('This report helps you spot issues that can delay registration, impact home loans, or create problems during', leftMargin, yPos, { width: contentWidth, lineGap: 2 });
            yPos += 14;
            doc.text('resale. 0 is best. Higher score = higher risk.', leftMargin, yPos, { width: contentWidth, lineGap: 2 });
            // Bold the specific parts manually or just leave as is for pdfkit simplicity
            yPos += 40;

            // Overall Risk Widget
            // Left Box (Grey)
            const widgetHeight = 60;
            const widgetWidth = contentWidth;
            doc.rect(leftMargin, yPos, widgetWidth * 0.7, widgetHeight).fill('#F3F4F6');

            // Right Box (Color)
            doc.rect(leftMargin + (widgetWidth * 0.7), yPos, widgetWidth * 0.3, widgetHeight).fill(riskLevelBoxFill);

            // Left Box Text
            doc.fillColor('#000000')
                .font('Helvetica-Bold')
                .fontSize(12)
                .text('Overall Risk', leftMargin + 15, yPos + 15);
            doc.font('Helvetica')
                .fontSize(11)
                .text(`${aiReport.riskScore} / 100`, leftMargin + 15, yPos + 35);

            // Right Box Text
            doc.fillColor('#FFFFFF')
                .font('Helvetica-Bold')
                .fontSize(14)
                .text(riskText, leftMargin + (widgetWidth * 0.7), yPos + 22, { align: 'center', width: widgetWidth * 0.3 });

            yPos += widgetHeight + 30;

            // How to use this report
            const howToHeight = 120;
            doc.rect(leftMargin, yPos, contentWidth, howToHeight).fill('#F3F4F6');

            // Fine grey border (can simulate with stroke)
            doc.lineWidth(1).strokeColor('#E5E7EB').rect(leftMargin, yPos, contentWidth, howToHeight).stroke();

            doc.fillColor('#000000')
                .font('Helvetica-Bold')
                .fontSize(12)
                .text('How to use this report', leftMargin + 15, yPos + 15);

            yPos += 45;
            doc.font('Helvetica')
                .fontSize(10)
                .text('• Each check has a risk score (0–100): 0 is best, higher means higher risk.', leftMargin + 15, yPos, { lineGap: 3 });
            yPos += 15;
            doc.text('• Start with items marked High Risk and finish the suggested actions before paying or signing.', leftMargin + 15, yPos, { lineGap: 3 });
            yPos += 15;
            doc.text('• If any High Risk item is unresolved, consult a property lawyer before proceeding.', leftMargin + 15, yPos, { lineGap: 3 });

            yPos += 30;
            doc.fillColor('#6B7280') // Gray
                .fontSize(9)
                .text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, leftMargin + 15, yPos);

            // --- CONTENT PAGE ---
            doc.addPage();
            drawGlobalHeader(1);

            yPos = 120;
            doc.fillColor('#000000')
                .font('Helvetica-Bold')
                .fontSize(16)
                .text('All checks summary', leftMargin, yPos);

            yPos += 25;
            doc.fillColor('#6B7280')
                .font('Helvetica')
                .fontSize(9)
                .text('Scan the top rows first (higher score = higher risk).', leftMargin, yPos);

            yPos += 20;

            // Table Header
            const tableWidth = contentWidth;
            const colWidths = [tableWidth * 0.4, tableWidth * 0.15, tableWidth * 0.25, tableWidth * 0.2];
            let currentX = leftMargin;

            const drawRow = (y, heights, fills, borders, rowData, isHeader, colors) => {
                let x = leftMargin;
                for (let i = 0; i < 4; i++) {
                    // Cell Background
                    doc.rect(x, y, colWidths[i], heights).fill(fills[i]);
                    // Cell Border
                    if (borders) {
                        doc.lineWidth(0.5).strokeColor('#E5E7EB').rect(x, y, colWidths[i], heights).stroke();
                    }

                    // Text
                    doc.fillColor(colors[i] || '#000000')
                        .font(isHeader ? 'Helvetica-Bold' : (i === 2 ? 'Courier' : 'Helvetica'))
                        .fontSize(9)
                        .text(rowData[i], x + 10, y + 10, { width: colWidths[i] - 20, align: (i === 1 ? 'right' : 'left') });

                    x += colWidths[i];
                }
            };

            // Draw Header
            drawRow(yPos, 30, ['#0B172A', '#0B172A', '#0B172A', '#0B172A'], true, ['Check', 'Score', 'Meter', 'Level'], true, ['#FFFFFF', '#FFFFFF', '#FFFFFF', '#FFFFFF']);
            yPos += 30;

            // Process checks - we want to assign mock scores based on logical mapping to make it look like the demo PDF
            // We sort them roughly by risk
            const checksArray = aiReport.checks || [];
            const displayChecks = checksArray.map(c => {
                let cLevelText = 'LOW RISK';
                let rowFillColor = '#DCFCE7';
                let icon = '';

                // Use the real score returned by the AI or wrappers
                let cScore = c.score || 0;

                if (c.status === 'Fail') {
                    cLevelText = 'HIGH RISK';
                    rowFillColor = '#FFE4E6';
                } else if (c.status === 'Warning') {
                    cLevelText = 'MEDIUM RISK';
                    rowFillColor = '#FEF3C7';
                } else {
                    cLevelText = 'LOW RISK';
                    rowFillColor = '#DCFCE7';
                }

                // Generate meter string: e.g. 5 hashes, 5 dots
                const hashCount = Math.round(cScore / 10);
                const meter = '#'.repeat(hashCount) + '.'.repeat(10 - hashCount);

                return {
                    title: `${c.title.toUpperCase().substring(0, 30)}`,
                    scoreStr: cScore.toFixed(1),
                    meter: meter,
                    levelText: cLevelText,
                    rowFill: rowFillColor,
                    scoreVal: cScore
                };
            }).sort((a, b) => b.scoreVal - a.scoreVal); // Highest score first

            // Draw Rows
            displayChecks.forEach((c) => {
                if (yPos > doc.page.height - 100) {
                    doc.addPage();
                    drawGlobalHeader(2); // In a real app we'd track page num properly
                    yPos = 120;
                }
                drawRow(yPos, 30, [c.rowFill, c.rowFill, c.rowFill, c.rowFill], true, [c.title, c.scoreStr, c.meter, c.levelText], false, ['#000000', '#000000', '#000000', '#000000']);
                yPos += 30;
            });

            // --- INDIVIDUAL CHECK PAGES ---
            let pageNum = 2; // We track page number to show in the header

            displayChecks.forEach((c) => {
                doc.addPage();
                pageNum++;
                drawGlobalHeader(pageNum);

                let y = 120;

                // 1. Title Bar (Dark Navy)
                doc.rect(leftMargin, y, contentWidth, 30).fill('#0B172A');
                doc.fillColor('#FFFFFF')
                    .font('Helvetica-Bold')
                    .fontSize(12)
                    .text(c.title, leftMargin + 15, y + 10);

                y += 45;

                // 2. Risk Info Box
                const boxHeight = 50;
                doc.rect(leftMargin, y, contentWidth * 0.7, boxHeight).fill('#F3F4F6');
                doc.rect(leftMargin + (contentWidth * 0.7), y, contentWidth * 0.3, boxHeight).fill(c.rowFill === '#FFE4E6' ? '#EF4444' : (c.rowFill === '#FEF3C7' ? '#F59E0B' : '#22C55E'));

                doc.fillColor('#000000')
                    .font('Helvetica-Bold')
                    .fontSize(10)
                    .text(`Risk score: `, leftMargin + 15, y + 15, { continued: true })
                    .font('Helvetica').text(`${c.scoreStr} / 100`);

                doc.font('Helvetica-Bold')
                    .text(`Risk level: `, leftMargin + 15, y + 30, { continued: true })
                    .font('Helvetica').text(`${c.levelText}`);

                doc.fillColor(c.rowFill === '#DCFCE7' ? '#166534' : (c.rowFill === '#FFE4E6' ? '#FFFFFF' : '#000000'))
                    .font('Helvetica-Bold')
                    .fontSize(12)
                    .text(c.levelText, leftMargin + (contentWidth * 0.7), y + 20, { align: 'center', width: contentWidth * 0.3 });

                y += boxHeight + 20;

                // 3. Risk Meter Graphic (5 Segments)
                doc.fillColor('#000000')
                    .font('Helvetica-Bold')
                    .fontSize(10)
                    .text('Risk meter', leftMargin, y);
                y += 15;

                const segmentWidth = contentWidth / 5;
                const meterColor = c.rowFill === '#FFE4E6' ? '#EF4444' : (c.rowFill === '#FEF3C7' ? '#F59E0B' : '#22C55E');
                const fillSegments = Math.ceil((c.scoreVal / 100) * 5);

                for (let i = 0; i < 5; i++) {
                    doc.rect(leftMargin + (i * segmentWidth), y, segmentWidth - 2, 10)
                        .fill(i < fillSegments ? meterColor : '#E5E7EB');
                }

                y += 40;

                // 4. Explanation Section
                // Attempt to match the check back to the original array to get the full findings text
                const originalCheckName = c.title.replace('   ', '').trim();
                const originalCheck = aiReport.checks.find(ac => ac.title.toUpperCase() === originalCheckName);
                const findingsText = originalCheck && originalCheck.findings ? originalCheck.findings : "No details provided.";
                const bulletPoints = (typeof findingsText === 'string' ? findingsText.split('|') : []).map(s => s.trim()).filter(s => s.length > 0);
                
                if (bulletPoints.length === 0) bulletPoints.push("No specific details provided for this check.");

                doc.fillColor('#000000')
                    .font('Helvetica-Bold')
                    .fontSize(12)
                    .text('Explanation', leftMargin, y);
                y += 20;

                // Calculate roughly how tall the box needs to be
                const textOptions = { width: contentWidth - 30, lineGap: 4 };
                let currentBoxY = y;
                let tempHeight = 20; // top padding

                bulletPoints.forEach(bp => {
                    tempHeight += doc.heightOfString(`• ${bp}`, textOptions) + 10;
                });

                doc.rect(leftMargin, currentBoxY, contentWidth, tempHeight).fill('#F3F4F6');
                doc.lineWidth(0.5).strokeColor('#E5E7EB').rect(leftMargin, currentBoxY, contentWidth, tempHeight).stroke();

                let textY = currentBoxY + 15;
                doc.fillColor('#374151').font('Helvetica').fontSize(10);
                bulletPoints.forEach(bp => {
                    doc.text(`• ${bp}`, leftMargin + 15, textY, textOptions);
                    textY += doc.heightOfString(`• ${bp}`, textOptions) + 10;
                });

                y = currentBoxY + tempHeight + 30;

                // 5. Suggested Actions
                doc.fillColor('#000000')
                    .font('Helvetica-Bold')
                    .fontSize(12)
                    .text('Suggested actions', leftMargin, y);
                y += 20;

                const actionsHeight = 80;
                doc.rect(leftMargin, y, contentWidth, actionsHeight).fill('#F3F4F6');
                doc.lineWidth(0.5).strokeColor('#E5E7EB').rect(leftMargin, y, contentWidth, actionsHeight).stroke();

                doc.fillColor('#374151').font('Helvetica').fontSize(10);
                if (c.rowFill === '#FFE4E6') {
                    doc.text("• HIGH PRIORITY: Consult a property lawyer immediately to review this specific discrepancy.", leftMargin + 15, y + 15, textOptions);
                    doc.text("• Halt any further payments or signing of agreements until resolved.", leftMargin + 15, y + 40, textOptions);
                } else if (c.rowFill === '#FEF3C7') {
                    doc.text("• Discuss this finding with the seller or builder for clarification.", leftMargin + 15, y + 15, textOptions);
                    doc.text("• Ensure missing documents or NOCs are obtained before final registration.", leftMargin + 15, y + 40, textOptions);
                } else {
                    doc.text("• No immediate action required. This check passed our standard verification.", leftMargin + 15, y + 15, textOptions);
                }
            });

            doc.end();

            stream.on('finish', () => {
                resolve({ success: true, pdfPath, pdfUrl: `/reports/report_${sessionId}.pdf` });
            });

            stream.on('error', (err) => {
                console.error("PDF generation stream error:", err);
                reject(err);
            });

        } catch (error) {
            console.error("PDF generation block error:", error);
            reject(error);
        }
    });
}
